"""Weekly drift-detection agent — wires the Aria Halberg persona to a Claude Code session.

Schedules a once-per-week (Monday 8am local) Claude Code session that
reads structurally-symmetric files across pipelines/{stocks,crypto,
options}/, asks Aria to compare them, and writes the categorized report
to docs/drift-reports/YYYY-MM-DD.md.

Two ways to run:
1. **Scheduled** via Claude Code's /schedule (preferred) — see register_with_scheduler().
2. **Ad-hoc** via ``uv run python -m trading_bot.shared.automation.drift_agent``
   to produce a one-off report on demand.

Module is deliberately small — it just builds the file pair list and the
prompt, then defers to ``trading_bot.shared.llm_transport`` for the call.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Tuple

PIPELINES = ("stocks", "crypto", "options")
PIPELINE_ROOT = Path("src/trading_bot/pipelines")
DRIFT_REPORT_ROOT = Path("docs/drift-reports")
ADR_ROOT = Path("docs/adrs")

# Files we expect to be structurally symmetric across pipelines.
# Add to this list as each pipeline phase ships.
SYMMETRIC_TARGETS = (
    "scout_debate.py",
    "entry_debate.py",
    "hold_debate.py",
    "position_monitor.py",
    "lesson_loop.py",
    "circuit_breaker.py",
    "adversarial.py",
    "event_streamer.py",
    "regime.py",
)


def find_pairs(targets: Iterable[str] = SYMMETRIC_TARGETS) -> List[Tuple[str, Path, str, Path]]:
    """Return (asset_a, path_a, asset_b, path_b) for every symmetric file pair across pipelines.

    Only includes pairs where both files exist on disk.
    """
    pairs: List[Tuple[str, Path, str, Path]] = []
    for target in targets:
        present: List[Tuple[str, Path]] = []
        for pipeline in PIPELINES:
            p = PIPELINE_ROOT / pipeline / target
            if p.exists():
                present.append((pipeline, p))
        # All unordered pairs from `present`.
        for i in range(len(present)):
            for j in range(i + 1, len(present)):
                pairs.append((*present[i], *present[j]))
    return pairs


def load_adrs() -> str:
    """Concatenate all ADR markdown files into a single brief block."""
    if not ADR_ROOT.exists():
        return "(no ADRs yet)"
    chunks: List[str] = []
    for p in sorted(ADR_ROOT.glob("*.md")):
        if p.name == "README.md":
            continue
        chunks.append(f"=== {p.name} ===\n{p.read_text()}")
    return "\n\n".join(chunks) if chunks else "(no ADRs yet)"


def build_file_pair_block(pairs: List[Tuple[str, Path, str, Path]]) -> str:
    """Render the pairs as a single text block for the persona prompt."""
    if not pairs:
        return "(no symmetric file pairs found across pipelines yet)"
    chunks: List[str] = []
    for a_asset, a_path, b_asset, b_path in pairs:
        chunks.append(
            f"--- pair: {a_asset}/{a_path.name} vs {b_asset}/{b_path.name} ---\n"
            f"=== {a_path} ===\n{a_path.read_text()}\n"
            f"=== {b_path} ===\n{b_path.read_text()}\n"
        )
    return "\n".join(chunks)


def run_drift_report(*, dry_run: bool = False) -> Path | None:
    """Build the prompt and (optionally) invoke the drift detector persona.

    Returns the report file path on success, or None if dry-run / no
    pairs to compare.
    """
    pairs = find_pairs()
    if not pairs:
        print("[drift-agent] no symmetric file pairs found yet — skipping run")
        return None

    sys.path.insert(0, str(Path("src").resolve()))
    from trading_bot.shared.personas.drift_detector import PERSONA
    from trading_bot.shared.personas._base import parse, render_prompt

    persona = parse(PERSONA)
    file_pair_block = build_file_pair_block(pairs)
    adr_block = load_adrs()
    rendered = render_prompt(
        persona,
        file_pair_block=file_pair_block,
        adr_block=adr_block,
    )

    if dry_run:
        print(rendered[:2000])
        print("…\n[drift-agent] dry-run only; not invoking LLM")
        return None

    from trading_bot.shared.llm_transport import get_transport

    transport = get_transport(role_name=persona.debate_role)
    response = transport.complete(
        system=rendered,
        messages=[{"role": "user", "content": "Produce the drift report now."}],
    )

    DRIFT_REPORT_ROOT.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    report_path = DRIFT_REPORT_ROOT / f"{today}.md"
    report_path.write_text(
        f"# Drift report — {today} UTC\n\n"
        f"Generated by {persona.full_name} ({persona.role_title}, {persona.years_experience}yr).\n"
        f"Model: {response.model}.\n\n"
        f"{response.text}\n"
    )
    print(f"[drift-agent] wrote {report_path}")
    return report_path


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print the assembled prompt to stdout; do NOT invoke the LLM (saves quota)",
    )
    args = parser.parse_args(argv)
    run_drift_report(dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
