"""Critical alert email builder. Used by Supervisor on drawdown breach,
daemon stall, account corruption, etc.
"""
from __future__ import annotations

import datetime as dt
from trading_bot.email_fill import Email


def build_critical_email(*, title: str, detail: str, severity: str = "HIGH") -> Email:
    subject = f"[CRITICAL] {title}"
    ts = dt.datetime.now(dt.timezone.utc).isoformat()
    body = (
        f"<h2 style='color:#c00'>[{severity}] {title}</h2>"
        f"<p><b>Timestamp (UTC):</b> {ts}</p>"
        f"<pre style='background:#f5f5f5;padding:12px;border-radius:6px'>{detail}</pre>"
        f"<p><i>This alert was generated by the trading bot supervisor. "
        f"It will be repeated up to once per hour while the condition persists.</i></p>"
    )
    return Email(subject=subject, html_body=body)
