"""Critical alert email builder. Used by Supervisor on drawdown breach,
daemon stall, account corruption, etc. Renders through the shared dark
email shell so Gmail/Apple Mail show it consistently with the rest of
the bot's output.
"""
from __future__ import annotations

import datetime as dt

from trading_bot.email_fill import Email
from trading_bot.email_shell import render_shell, section


_SEVERITY_KIND = {
    "LOW":      "info",
    "MEDIUM":   "warn",
    "HIGH":     "bad",
    "CRITICAL": "bad",
}


def build_critical_email(*, title: str, detail: str, severity: str = "HIGH") -> Email:
    """Render a CRITICAL alert email through the dark shell.

    `severity` is uppercased text (LOW / MEDIUM / HIGH / CRITICAL) and
    drives the section color rail. Detail is a free-form string, rendered
    inside a <pre> for monospace + line breaks. The shell handles the
    outer dark theme + Gmail color-scheme declarations."""
    subject = f"[CRITICAL] {title}"
    sev_upper = severity.upper()
    sev_kind = _SEVERITY_KIND.get(sev_upper, "bad")
    now = dt.datetime.now(dt.timezone.utc)

    detail_html = (
        # Use mid-tone monospace block — explicit dark bg so even if a
        # client overrides the parent, this stays legible.
        f'<pre style="margin:0;padding:12px;background:#0a1322;'
        f'border:1px solid #26334a;border-radius:6px;color:#f1f5f9;'
        f"font-family:'SF Mono','JetBrains Mono',Menlo,Consolas,monospace;"
        f'font-size:13px;line-height:1.55;white-space:pre-wrap;'
        f'word-wrap:break-word">{detail}</pre>'
        f'<p style="margin:12px 0 0;color:#cbd5e1;font-size:12px;'
        f'font-style:italic">'
        f'Auto-generated by trading-bot supervisor. Repeats up to once per '
        f'hour while the condition persists.</p>'
    )

    body = section(
        title=f"{sev_upper} — {title}",
        glyph="⚠",
        body=detail_html,
        severity=sev_kind,
    )

    html = render_shell(
        title=f"Critical · {title}",
        status=("bad" if sev_kind == "bad" else "warn"),
        timestamp_et=now.strftime("%a, %b %d · %H:%M UTC"),
        body_sections=[body],
    )
    return Email(subject=subject, html_body=html)
