"""initial schema

Revision ID: b18b7d0e5c78
Revises: 
Create Date: 2026-04-27 23:14:18.687889+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18b7d0e5c78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promoted_by', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equity_high_water_mark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_high_water_mark_account'), 'equity_high_water_mark', ['account'], unique=False)
    op.create_index(op.f('ix_equity_high_water_mark_recorded_at'), 'equity_high_water_mark', ['recorded_at'], unique=False)
    op.create_table('heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('last_action', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_ts'), 'heartbeats', ['ts'], unique=False)
    op.create_table('regime_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('spy_breadth', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_history_recorded_at'), 'regime_history', ['recorded_at'], unique=False)
    op.create_table('role_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('kpi_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_kpis_recorded_at'), 'role_kpis', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_role_kpis_role_name'), 'role_kpis', ['role_name'], unique=False)
    op.create_table('role_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_runs_role_name'), 'role_runs', ['role_name'], unique=False)
    op.create_index(op.f('ix_role_runs_started_at'), 'role_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_runs_started_at'), table_name='role_runs')
    op.drop_index(op.f('ix_role_runs_role_name'), table_name='role_runs')
    op.drop_table('role_runs')
    op.drop_index(op.f('ix_role_kpis_role_name'), table_name='role_kpis')
    op.drop_index(op.f('ix_role_kpis_recorded_at'), table_name='role_kpis')
    op.drop_table('role_kpis')
    op.drop_index(op.f('ix_regime_history_recorded_at'), table_name='regime_history')
    op.drop_table('regime_history')
    op.drop_index(op.f('ix_heartbeats_ts'), table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index(op.f('ix_equity_high_water_mark_recorded_at'), table_name='equity_high_water_mark')
    op.drop_index(op.f('ix_equity_high_water_mark_account'), table_name='equity_high_water_mark')
    op.drop_table('equity_high_water_mark')
    op.drop_table('config_history')
    # ### end Alembic commands ###
