"""leaderboard and evolution_runs

Revision ID: 560bb7ac8682
Revises: b18b7d0e5c78
Create Date: 2026-04-28 01:57:40.196300+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560bb7ac8682'
down_revision: Union[str, Sequence[str], None] = 'b18b7d0e5c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evolution_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template_name', sa.String(length=64), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('best_fitness', sa.Float(), nullable=True),
    sa.Column('best_params_hash', sa.String(length=64), nullable=True),
    sa.Column('auto_promoted', sa.Integer(), nullable=False),
    sa.Column('promotion_gate_pass', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=64), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('alpha_vs_spy_x', sa.Float(), nullable=False),
    sa.Column('sortino', sa.Float(), nullable=False),
    sa.Column('max_dd_pct', sa.Float(), nullable=False),
    sa.Column('folds_passed', sa.Integer(), nullable=False),
    sa.Column('folds_total', sa.Integer(), nullable=False),
    sa.Column('fitness_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_fitness_score'), 'leaderboard', ['fitness_score'], unique=False)
    op.create_index(op.f('ix_leaderboard_params_hash'), 'leaderboard', ['params_hash'], unique=False)
    op.create_index(op.f('ix_leaderboard_recorded_at'), 'leaderboard', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_leaderboard_template_name'), 'leaderboard', ['template_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_template_name'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_recorded_at'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_params_hash'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_fitness_score'), table_name='leaderboard')
    op.drop_table('leaderboard')
    op.drop_table('evolution_runs')
    # ### end Alembic commands ###
