"""calibration_runs and promoter_halts

Revision ID: 4674521a4b84
Revises: 560bb7ac8682
Create Date: 2026-04-28 02:36:19.717268+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4674521a4b84'
down_revision: Union[str, Sequence[str], None] = '560bb7ac8682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('template_name', sa.String(length=64), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('spearman_corr', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_runs_recorded_at'), 'calibration_runs', ['recorded_at'], unique=False)
    op.create_table('promoter_halts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('halted_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('set_by', sa.String(length=64), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promoter_halts_halted_until'), 'promoter_halts', ['halted_until'], unique=False)
    op.add_column('leaderboard', sa.Column('per_trade_predictions_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard', 'per_trade_predictions_json')
    op.drop_index(op.f('ix_promoter_halts_halted_until'), table_name='promoter_halts')
    op.drop_table('promoter_halts')
    op.drop_index(op.f('ix_calibration_runs_recorded_at'), table_name='calibration_runs')
    op.drop_table('calibration_runs')
    # ### end Alembic commands ###
