"""fallback_flags and hold_spy_transitions

Revision ID: 66f56829c36d
Revises: 4674521a4b84
Create Date: 2026-04-28 02:43:58.145942+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f56829c36d'
down_revision: Union[str, Sequence[str], None] = '4674521a4b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fallback_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fallback_active', sa.Integer(), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('set_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fallback_flags_set_at'), 'fallback_flags', ['set_at'], unique=False)
    op.create_table('hold_spy_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fallback_flag_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hold_spy_transitions_fallback_flag_id'), 'hold_spy_transitions', ['fallback_flag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hold_spy_transitions_fallback_flag_id'), table_name='hold_spy_transitions')
    op.drop_table('hold_spy_transitions')
    op.drop_index(op.f('ix_fallback_flags_set_at'), table_name='fallback_flags')
    op.drop_table('fallback_flags')
    # ### end Alembic commands ###
