"""anthropic cost log + template proposals

Revision ID: fb03c506f6b4
Revises: 66f56829c36d
Create Date: 2026-04-28 02:53:38.302265+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb03c506f6b4'
down_revision: Union[str, Sequence[str], None] = '66f56829c36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anthropic_cost_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anthropic_cost_log_called_at'), 'anthropic_cost_log', ['called_at'], unique=False)
    op.create_table('cost_halts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('halted_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_halts_halted_until'), 'cost_halts', ['halted_until'], unique=False)
    op.create_table('template_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('expected_regime', sa.String(length=32), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('tests', sa.Text(), nullable=False),
    sa.Column('params_to_search_json', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('review_findings_json', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_proposals_name'), 'template_proposals', ['name'], unique=False)
    op.create_index(op.f('ix_template_proposals_proposed_at'), 'template_proposals', ['proposed_at'], unique=False)
    op.create_index(op.f('ix_template_proposals_review_status'), 'template_proposals', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_proposals_review_status'), table_name='template_proposals')
    op.drop_index(op.f('ix_template_proposals_proposed_at'), table_name='template_proposals')
    op.drop_index(op.f('ix_template_proposals_name'), table_name='template_proposals')
    op.drop_table('template_proposals')
    op.drop_index(op.f('ix_cost_halts_halted_until'), table_name='cost_halts')
    op.drop_table('cost_halts')
    op.drop_index(op.f('ix_anthropic_cost_log_called_at'), table_name='anthropic_cost_log')
    op.drop_table('anthropic_cost_log')
    # ### end Alembic commands ###
